openapi: 3.0.1
info:
  title: Credentialing API
  description: Provides verification process to ensure companies requesting reports are legitimate.
  version: v1
paths:
  /v1/applications:
    post:
      tags:
        - Application
      summary: Submits an application for the credentialing
      operationId: submitapplication
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
          text/json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
      responses:
        '201':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}':
    put:
      tags:
        - Application
      summary: Updates the application info
      description: Updates the application info
      operationId: updateapplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
          text/json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ApplicationDto'
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}/transitions':
    post:
      tags:
        - Application
      summary: Makes status transitions for the application
      description: Makes status transitions for the application
      operationId: transitions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationDetailsDto'
          text/json:
            schema:
              $ref: '#/components/schemas/VerificationDetailsDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/VerificationDetailsDto'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}/verification':
    get:
      tags:
        - Application
      summary: Gets the verification details
      description: Gets the verification details
      operationId: getverificationdetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationDetailsDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}/onsite-inspection-payment':
    post:
      tags:
        - On-Site Inspection
      summary: Adds a payment to the application
      description: Submits payment for On-site Inspection
      operationId: submitpayment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentInfoDto'
          text/json:
            schema:
              $ref: '#/components/schemas/PaymentInfoDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PaymentInfoDto'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}/questionnaire':
    post:
      tags:
        - Questionnaire
      summary: Submits a questionnaire
      description: Submits the Questionnaire
      operationId: submitquestionnaire
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireDto'
          text/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/QuestionnaireDto'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    get:
      tags:
        - Questionnaire
      summary: Gets the questionnaire
      description: Gets the Questionnaire
      operationId: getquestionnaire
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/v1/applications/{id}/onsite-inspection':
    post:
      tags:
        - On-Site Inspection
      summary: Submits an onsite inspection info
      description: Submits the On-site Inspection Info
      operationId: submitonsiteinspection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionInfoDto'
          text/json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionInfoDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionInfoDto'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      tags:
        - On-Site Inspection
      summary: Updates details of the on-site inspection
      description: Updates the On-site Inspection Info
      operationId: updateonsiteinspection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionDetailsDto'
          text/json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionDetailsDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OnsiteInspectionDetailsDto'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    Credentialing:
      type: object
      properties:
        companyPhone:
          type: string
          nullable: true
        stateofIncorporation:
          type: string
          nullable: true
        dba:
          type: string
          nullable: true
        companyWebsite:
          type: string
          nullable: true
        taxClassification:
          type: string
          nullable: true
        isAutoApprovedBySales:
          type: boolean
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    CreditCredentialing:
      type: object
      properties:
        isExemptFromOnSiteInspection:
          type: boolean
        onSiteInspectionExemptionReason:
          type: string
          nullable: true
      additionalProperties: false
    ApplicationDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
        companyName:
          type: string
          nullable: true
        streetAddress:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        state:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true
        taxId:
          type: string
          nullable: true
        credentialingApplication:
          $ref: '#/components/schemas/Credentialing'
        creditCredentialingApplication:
          $ref: '#/components/schemas/CreditCredentialing'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    CredentialingDetails:
      type: object
      properties:
        companyCredentialingStatus:
          type: string
          nullable: true
        userCredentialingStatus:
          type: string
          nullable: true
        isLNEINMatch:
          type: boolean
          nullable: true
        isLNNameMatch:
          type: boolean
          nullable: true
        isLNAddressMatch:
          type: boolean
          nullable: true
        isSOSNameMatch:
          type: boolean
          nullable: true
        isSOSAddressMatch:
          type: boolean
          nullable: true
        isBusinessLicenseProvided:
          type: boolean
          nullable: true
        isW9Provided:
          type: boolean
          nullable: true
        isCompanyWebsiteWithAddressMatch:
          type: boolean
          nullable: true
        isCompanyWebsitePhoneMatch:
          type: boolean
          nullable: true
        emailMatchesUserNameAndCompanyEmailDomain:
          type: boolean
          nullable: true
        isNameMatchesWithTitleOnWebsite:
          type: boolean
          nullable: true
        isNameMatchesWithTitleOnLinkedIn:
          type: boolean
          nullable: true
        applicantProvidedW9OrBLDuringCompanyVerification:
          type: boolean
          nullable: true
      additionalProperties: false
    CreditCredentialingDetails:
      type: object
      additionalProperties: false
    VerificationDetailsDto:
      type: object
      properties:
        applicationType:
          type: string
          nullable: true
        applicationStatus:
          type: string
          nullable: true
        agentName:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true
        credentialing:
          $ref: '#/components/schemas/CredentialingDetails'
        creditCredentialing:
          $ref: '#/components/schemas/CreditCredentialingDetails'
      additionalProperties: false
    PaymentInfoDto:
      type: object
      properties:
        paidBy:
          type: string
          nullable: true
        paidOn:
          type: string
          format: date-time
      additionalProperties: false
    TaxClassification:
      enum:
        - IndividualSoleProprietor
        - CCorporation
        - SCorporation
        - Partnership
        - TrusteeEstate
        - LimitedLiabilityCompany
        - NonprofitOrganization
      type: string
    BusinessDuration:
      enum:
        - LessThanOneYear
        - OneYearOrMore
      type: string
    BusinessLocation:
      enum:
        - MyHome
        - CommercialOfficeSpace
      type: string
    Industry:
      enum:
        - Automotive
        - Banks
        - Clothing
        - DepartmentVariety
        - EducationEmployment
        - FinancePersonal
        - Groceries
        - HomeOfficeFurnishings
        - Insurance
        - JewelryCameras
        - Contractors
        - LumberBuildingMaterials
        - MedicalRelatedHealth
        - TravelEntertainment
        - OilCompanies
        - PersonalServices
        - CreditUnionsAndFinanceCompanies
        - RealEstateAndPublicAccommodations
        - SportingGoods
        - FarmAndGardenSupplies
        - UtilitiesAndFuel
        - Government
        - Wholesale
        - Advertising
        - CollectionServices
        - Miscellaneous
        - Technology
        - Manufacturing
        - Other
      type: string
    Statement:
      type: object
      properties:
        number:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        isChecked:
          type: boolean
      additionalProperties: false
    QuestionnaireDto:
      type: object
      properties:
        taxClassification:
          $ref: '#/components/schemas/TaxClassification'
        businessDuration:
          $ref: '#/components/schemas/BusinessDuration'
        businessLocation:
          $ref: '#/components/schemas/BusinessLocation'
        businessIndustry:
          $ref: '#/components/schemas/Industry'
        businessIndustryDetails:
          type: string
          nullable: true
        estimatedCreditReportsVolume:
          type: integer
          format: int32
        statements:
          type: array
          items:
            $ref: '#/components/schemas/Statement'
          nullable: true
        didCompanyQualifyForCreditReports:
          type: boolean
      additionalProperties: false
    OnsiteInspectionInfoDto:
      type: object
      properties:
        applicationId:
          type: string
          nullable: true
        primaryContactFirstName:
          type: string
          nullable: true
        primaryContactLastName:
          type: string
          nullable: true
        primaryContactEmail:
          type: string
          nullable: true
        primaryPhone:
          type: string
          nullable: true
        primaryPhoneExt:
          type: string
          nullable: true
        secondaryContactFirstName:
          type: string
          nullable: true
        secondaryContactLastName:
          type: string
          nullable: true
        secondaryContactEmail:
          type: string
          nullable: true
        secondaryPhone:
          type: string
          nullable: true
        secondaryPhoneExt:
          type: string
          nullable: true
      additionalProperties: false
    OnsiteInspectionDetailsDto:
      type: object
      properties:
        status:
          type: string
          nullable: true
        statusDetails:
          type: string
          nullable: true
        nextActionOn:
          type: string
          format: date-time
          nullable: true
        finalOnsiteInspectionStatus:
          type: string
          nullable: true
        rawDataQuestionnaire:
          type: string
          nullable: true
      additionalProperties: false
